development:  
  redis_url: http://localhost:6379
  namespace: raptor

test:  
  redis_url: http://localhost:6379
  namespace: raptor_test

production:  
  redis_url: <%= ENV['REDISTOGO_URL'] %>
  namespace: raptor
